runtime: nodejs10
instance_class: F1
service: api
handlers:
  - url: /.*
    script: auto
    secure: always
env_variables:
  HOST: '0.0.0.0'
  PORT: '8080'
  ALLOW_ORIGIN: 'https://techbookranking.appspot.com'
